services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amithaliz_app_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/usr/src/app
      # Keep node_modules inside container to avoid host OS mismatch
      - /usr/src/app/node_modules
    command: sh -c "npm install --no-audit --no-fund && npm run dev"
